testing pipeline

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -20,6 +20,19 @@ jobs:
             TAG=$(git rev-parse --short HEAD)
             docker build -t $DOCKER_USERNAME/portfolio-fe:$TAG ./portfolio-frontend
             echo "export IMAGE_TAG=${TAG}" >> $BASH_ENV
+
+      - run:
+          name: Validate IMAGE_TAG
+          command: |
+            if [ -z "$IMAGE_TAG" ]; then
+              echo "IMAGE_TAG is empty!"
+              exit 1
+            fi
+
+            if ! echo "$IMAGE_TAG" | grep -Eq '^[a-zA-Z0-9_.-]+$'; then
+              echo "IMAGE_TAG contains invalid characters!"
+              exit 1
+            fi
       
       - run:
           name: Docker Hub Login
